//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HolidayLabelsAndListsHelper.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HolidayLabelsAndListsHelper.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All sections processed OK.
        /// </summary>
        internal static string AllSectionsProcessedOKMsg {
            get {
                return ResourceManager.GetString("AllSectionsProcessedOKMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bag_Labels_{0}_{1}_{2}.docx.
        /// </summary>
        internal static string BagLabelBaseFilename {
            get {
                return ResourceManager.GetString("BagLabelBaseFilename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Christmas.
        /// </summary>
        internal static string ChristmasFolderName {
            get {
                return ResourceManager.GetString("ChristmasFolderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found {0} data sections..
        /// </summary>
        internal static string CountOfDataSectionsMsg {
            get {
                return ResourceManager.GetString("CountOfDataSectionsMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Writing {0} {1} to file {2}.
        /// </summary>
        internal static string CountWritingMsg {
            get {
                return ResourceManager.GetString("CountWritingMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found {0} data sections..
        /// </summary>
        internal static string DataSectionsFoundMsg {
            get {
                return ResourceManager.GetString("DataSectionsFoundMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click &quot;Yes&quot; to confirm deletion of backup files..
        /// </summary>
        internal static string DelBackupConfirmPrompt {
            get {
                return ResourceManager.GetString("DelBackupConfirmPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm File Deletion.
        /// </summary>
        internal static string DelBackupConfirmTitle {
            get {
                return ResourceManager.GetString("DelBackupConfirmTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while trying to delete backup files. The error text is: {0}.
        /// </summary>
        internal static string DelBackupErrorMsg {
            get {
                return ResourceManager.GetString("DelBackupErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Files From Previous Years.
        /// </summary>
        internal static string DeleteOldFilesTitle {
            get {
                return ResourceManager.GetString("DeleteOldFilesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HLLDocumentation - General.
        /// </summary>
        internal static string DocGeneralTitle {
            get {
                return ResourceManager.GetString("DocGeneralTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donor_List_{0}_{1}_{2}.xlsx.
        /// </summary>
        internal static string DonorListBasefilename {
            get {
                return ResourceManager.GetString("DonorListBasefilename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donor List, {0}, {1}, {2}.
        /// </summary>
        internal static string DonorListHeader {
            get {
                return ResourceManager.GetString("DonorListHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} DL {2}.
        /// </summary>
        internal static string DonorListWorksheetName {
            get {
                return ResourceManager.GetString("DonorListWorksheetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully added {0} label and/or list files.
        /// </summary>
        internal static string FileAddingSuccessMsg {
            get {
                return ResourceManager.GetString("FileAddingSuccessMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully created file {0} .
        /// </summary>
        internal static string FileCreationSuccessMsg {
            get {
                return ResourceManager.GetString("FileCreationSuccessMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred trying to work with file {0}.
        ///The error message was {1}. Here is the stack trace: {2}.
        /// </summary>
        internal static string FileExceptionErrorMsg {
            get {
                return ResourceManager.GetString("FileExceptionErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File {0} does not exist..
        /// </summary>
        internal static string FileNotFoundMsg {
            get {
                return ResourceManager.GetString("FileNotFoundMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Not Found.
        /// </summary>
        internal static string FileNotFoundTitle {
            get {
                return ResourceManager.GetString("FileNotFoundTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel Files (*.XLS;*XLS?)|*.XLS;*.XLS?.
        /// </summary>
        internal static string FileSpecFilterExcel {
            get {
                return ResourceManager.GetString("FileSpecFilterExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only the Two Most Recent Years.
        /// </summary>
        internal static string GenerateAllYearsNoButtonText {
            get {
                return ResourceManager.GetString("GenerateAllYearsNoButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to generate all labels and lists, or only those for the two most recent years? Generating them for only the most recent two years saves disk space and is a few seconds faster. (You can always come back later and generate the files for all years.).
        /// </summary>
        internal static string GenerateAllYearsPrompt {
            get {
                return ResourceManager.GetString("GenerateAllYearsPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Labels and Lists for Which Years?.
        /// </summary>
        internal static string GenerateAllYearsTitle {
            get {
                return ResourceManager.GetString("GenerateAllYearsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Years.
        /// </summary>
        internal static string GenerateAllYearsYesButtonText {
            get {
                return ResourceManager.GetString("GenerateAllYearsYesButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generating output files....
        /// </summary>
        internal static string GeneratingOutputFilesMsg {
            get {
                return ResourceManager.GetString("GeneratingOutputFilesMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gift_Labels_{0}_{1}_{2}.docx.
        /// </summary>
        internal static string GiftLabelBaseFilename {
            get {
                return ResourceManager.GetString("GiftLabelBaseFilename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please include gift receipt..
        /// </summary>
        internal static string GiftReceiptRequest {
            get {
                return ResourceManager.GetString("GiftReceiptRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} does not appear to b e a valid Excel worksheet..
        /// </summary>
        internal static string InvalidWorksheetMsg {
            get {
                return ResourceManager.GetString("InvalidWorksheetMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master_List_{0}_{1}_{2}.xlsx.
        /// </summary>
        internal static string MasterListBasefilename {
            get {
                return ResourceManager.GetString("MasterListBasefilename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master List, {0}, {1}, {2}.
        /// </summary>
        internal static string MasterListHeader {
            get {
                return ResourceManager.GetString("MasterListHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} ML {2}.
        /// </summary>
        internal static string MasterListWorksheetName {
            get {
                return ResourceManager.GetString("MasterListWorksheetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --- NO DATA ---.
        /// </summary>
        internal static string NoDataMsg {
            get {
                return ResourceManager.GetString("NoDataMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No files match the selected criteria..
        /// </summary>
        internal static string NoMatchingFilesMsg {
            get {
                return ResourceManager.GetString("NoMatchingFilesMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select different criteria for Document Type to View, Year, and/or Donor.
        /// </summary>
        internal static string NoMatchingFilesTooltip {
            get {
                return ResourceManager.GetString("NoMatchingFilesTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no label or list files available for viewing. Please click &quot;Create Labels and Lists&quot; to generate them..
        /// </summary>
        internal static string NoOutputFilesMsg {
            get {
                return ResourceManager.GetString("NoOutputFilesMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Output Files.
        /// </summary>
        internal static string NoOutputFilesTitle {
            get {
                return ResourceManager.GetString("NoOutputFilesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No imported VESTA data found. Please click &quot;Process VESTA Reports&quot; to import data from one or more reports..
        /// </summary>
        internal static string NothingImportedMsg {
            get {
                return ResourceManager.GetString("NothingImportedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Imported VESTA Data.
        /// </summary>
        internal static string NothingImportedTitle {
            get {
                return ResourceManager.GetString("NothingImportedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You may now close this window..
        /// </summary>
        internal static string OKToCloseMsg {
            get {
                return ResourceManager.GetString("OKToCloseMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing report {0}.
        /// </summary>
        internal static string OpeningReportMsg {
            get {
                return ResourceManager.GetString("OpeningReportMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        internal static string OtherFolderName {
            get {
                return ResourceManager.GetString("OtherFolderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Bpage &amp;P of &amp;N.
        /// </summary>
        internal static string PageNumbers {
            get {
                return ResourceManager.GetString("PageNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Participant_List_{0}_{1}.xlsx.
        /// </summary>
        internal static string ParticipantListBasefilename {
            get {
                return ResourceManager.GetString("ParticipantListBasefilename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Participant List, {0}, {1}.
        /// </summary>
        internal static string ParticipantListHeader {
            get {
                return ResourceManager.GetString("ParticipantListHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Participant_Summary_Labels_{0}.docx.
        /// </summary>
        internal static string ParticipantSummaryLabelsBaseFilename {
            get {
                return ResourceManager.GetString("ParticipantSummaryLabelsBaseFilename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postcard_Labels_{0}_{1}.docx.
        /// </summary>
        internal static string PostcardLabelBaseFilename {
            get {
                return ResourceManager.GetString("PostcardLabelBaseFilename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing cancelled..
        /// </summary>
        internal static string ProcessingCancelledMsg {
            get {
                return ResourceManager.GetString("ProcessingCancelledMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing data section {0} of {1}.
        /// </summary>
        internal static string ProcessingDataSectionsMsg {
            get {
                return ResourceManager.GetString("ProcessingDataSectionsMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report results.
        /// </summary>
        internal static string ResultsSheetDefaultName {
            get {
                return ResourceManager.GetString("ResultsSheetDefaultName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching for data sections in this VESTA report....
        /// </summary>
        internal static string SearchingForDataSectionsMsg {
            get {
                return ResourceManager.GetString("SearchingForDataSectionsMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All sections processed OK.
        /// </summary>
        internal static string SectionsProcessedSuccessMsg {
            get {
                return ResourceManager.GetString("SectionsProcessedSuccessMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing data section {0} of {1}....
        /// </summary>
        internal static string SectionXOfYMsg {
            get {
                return ResourceManager.GetString("SectionXOfYMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Years.
        /// </summary>
        internal static string SelectYears {
            get {
                return ResourceManager.GetString("SelectYears", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} not found in {1}.
        /// </summary>
        internal static string SheetNotFoundInFileMsg {
            get {
                return ResourceManager.GetString("SheetNotFoundInFileMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only {0} sections processed OK (out of {1}).
        /// </summary>
        internal static string SomeSectionsNotProcessedMsg {
            get {
                return ResourceManager.GetString("SomeSectionsNotProcessedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing report {0}.
        /// </summary>
        internal static string StartingEachReportMsg {
            get {
                return ResourceManager.GetString("StartingEachReportMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanksgiving_Delivery_List_{0}.xlsx.
        /// </summary>
        internal static string ThanksgivingDeliveryBaseFilename {
            get {
                return ResourceManager.GetString("ThanksgivingDeliveryBaseFilename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanksgiving Delivery List, {0}.
        /// </summary>
        internal static string ThanksgivingDeliveryListHeader {
            get {
                return ResourceManager.GetString("ThanksgivingDeliveryListHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanksgiving Delivery List.
        /// </summary>
        internal static string ThanksgivingDeliveryListSheetName {
            get {
                return ResourceManager.GetString("ThanksgivingDeliveryListSheetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanksgiving.
        /// </summary>
        internal static string ThanksgivingFolderName {
            get {
                return ResourceManager.GetString("ThanksgivingFolderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} report type is unknown..
        /// </summary>
        internal static string UnknownReportTypeMsg {
            get {
                return ResourceManager.GetString("UnknownReportTypeMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing {0} VESTA Reports.
        /// </summary>
        internal static string VestaReportCountMsg {
            get {
                return ResourceManager.GetString("VestaReportCountMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error during processing of the VESTA reports. The error text is:  {0}.
        /// </summary>
        internal static string VestaReportExceptionMsg {
            get {
                return ResourceManager.GetString("VestaReportExceptionMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting processing of VESTA reports....
        /// </summary>
        internal static string VestaReportProcessingStartMsg {
            get {
                return ResourceManager.GetString("VestaReportProcessingStartMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully imported {0} VESTA Reports.
        /// </summary>
        internal static string VestaReportProcessingSuccessMsg {
            get {
                return ResourceManager.GetString("VestaReportProcessingSuccessMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select one or more VESTA Reports.
        /// </summary>
        internal static string VestaReportSelectTitle {
            get {
                return ResourceManager.GetString("VestaReportSelectTitle", resourceCulture);
            }
        }
    }
}
