//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HolidayLabelsAndLists.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HolidayLabelsAndLists.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        internal static string CloseBtnCaption {
            get {
                return ResourceManager.GetString("CloseBtnCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Backup Files.
        /// </summary>
        internal static string DelBackupsBtnCaption {
            get {
                return ResourceManager.GetString("DelBackupsBtnCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Files From Previous Years.
        /// </summary>
        internal static string DelOldFilesBtnCaption {
            get {
                return ResourceManager.GetString("DelOldFilesBtnCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///&lt;head&gt;
        ///	&lt;title&gt;Holiday Labels and Lists&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body style=&quot;cursor: auto;&quot;&gt;
        ///&lt;h1 style=&quot;text-align: center;&quot;&gt;Holiday Labels and Lists User Documentation&lt;/h1&gt;
        ///
        ///&lt;h2&gt;Introduction&lt;/h2&gt;
        ///
        ///&lt;p&gt;The Holiday Labels and Lists program (&amp;quot;HLL&amp;quot;)&amp;nbsp;is meant to be used in connection with Valley&amp;#39;s holiday programs. It streamlines the process of creating bag and gift labels, master and donor lists, participant lists, and postcard labels from VESTA reports.&lt;/p&gt;
        ///
        ///&lt;p&gt;The focus of HLL&amp;#39;s display  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Doc_HTML {
            get {
                return ResourceManager.GetString("Doc_HTML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string ExitBtnCaption {
            get {
                return ResourceManager.GetString("ExitBtnCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string HelpBtnCaption {
            get {
                return ResourceManager.GetString("HelpBtnCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Output Files.
        /// </summary>
        internal static string MaintBtnCaption {
            get {
                return ResourceManager.GetString("MaintBtnCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Files.
        /// </summary>
        internal static string SaveFilesBtnCaption {
            get {
                return ResourceManager.GetString("SaveFilesBtnCaption", resourceCulture);
            }
        }
    }
}
