//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HolidayLabelsAndLists.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HolidayLabelsAndLists.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P:\\HolidayArchives\\.
        /// </summary>
        internal static string ArchiveStartFolder {
            get {
                return ResourceManager.GetString("ArchiveStartFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse....
        /// </summary>
        internal static string BrowseBtnCaption {
            get {
                return ResourceManager.GetString("BrowseBtnCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string CancelBtnCaption {
            get {
                return ResourceManager.GetString("CancelBtnCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        internal static string CloseBtnCaption {
            get {
                return ResourceManager.GetString("CloseBtnCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Backup Files.
        /// </summary>
        internal static string DelBackupsBtnCaption {
            get {
                return ResourceManager.GetString("DelBackupsBtnCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have chosen to delete all labels and lists, except participant lists, from the years {}. Click \&quot;Yes\&quot; to confirm. Otherwise, click \&quot;No\&quot; or \&quot;Cancel.\&quot;.
        /// </summary>
        internal static string DeleteOldConfirmation {
            get {
                return ResourceManager.GetString("DeleteOldConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string DelOldBackupsGoButtonCaption {
            get {
                return ResourceManager.GetString("DelOldBackupsGoButtonCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Files From Previous Years.
        /// </summary>
        internal static string DelOldFilesDialogBtnCaption {
            get {
                return ResourceManager.GetString("DelOldFilesDialogBtnCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination.
        /// </summary>
        internal static string DestLabelText {
            get {
                return ResourceManager.GetString("DestLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.01 Transitional//EN&quot;&gt;
        ///&lt;html&gt;
        ///  &lt;head&gt;
        ///
        ///    &lt;meta http-equiv=&quot;content-type&quot; content=&quot;text/html; charset=UTF-8&quot;&gt;
        ///    &lt;title&gt;HLL_Doc&lt;/title&gt;
        ///  &lt;/head&gt;
        ///  &lt;body&gt;
        ///    &lt;html&gt;&lt;br&gt;
        ///    &lt;head&gt;&lt;br&gt;
        ///    &lt;title&gt;Holiday Labels and Lists&lt;/title&gt;
        ///    &lt;/head&gt;
        ///    &lt;body style=&quot;cursor: auto;&quot;&gt;
        ///    &lt;h1 style=&quot;text-align: center;&quot;&gt;Holiday Labels and Lists User
        ///    Documentation&lt;/h1&gt;
        ///    &lt;hr/&gt;
        ///    &lt;h2&gt;Introduction&lt;/h2&gt;
        ///    &lt;p&gt;The Holiday Labels and Lists program(&amp;quot;HL [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Doc_HTML {
            get {
                return ResourceManager.GetString("Doc_HTML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Type(s).
        /// </summary>
        internal static string DocTypeLabelText {
            get {
                return ResourceManager.GetString("DocTypeLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Types#Bag Labels#Gift Labels#Donor and Master List#Participant List#Postcard Labels.
        /// </summary>
        internal static string DocumentTypes {
            get {
                return ResourceManager.GetString("DocumentTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string ExitBtnCaption {
            get {
                return ResourceManager.GetString("ExitBtnCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.01 Transitional//EN&quot;&gt;
        ///&lt;html&gt;
        ///  &lt;head&gt;
        ///
        ///    &lt;meta http-equiv=&quot;content-type&quot; content=&quot;text/html; charset=UTF-8&quot;&gt;
        ///    &lt;title&gt;Output File Management&lt;/title&gt;
        ///  &lt;/head&gt;
        ///  &lt;body&gt;
        ///    &lt;h1&gt;HLL Output File Management&lt;/h1&gt;
        ///    The File Management window offers you several functions designed to
        ///    help you reduce clutter, save disk space, and preserve HLL&apos;s output
        ///    files (the label and list documents). Here are brief summaries of
        ///    the functions:&lt;br&gt;
        ///    &lt;br&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FileManagementHTML {
            get {
                return ResourceManager.GetString("FileManagementHTML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string HelpBtnCaption {
            get {
                return ResourceManager.GetString("HelpBtnCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include Backup Files.
        /// </summary>
        internal static string IncludeBackupsChkCaption {
            get {
                return ResourceManager.GetString("IncludeBackupsChkCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Output Files.
        /// </summary>
        internal static string MaintBtnCaption {
            get {
                return ResourceManager.GetString("MaintBtnCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no files old enough to be deleted..
        /// </summary>
        internal static string MsgNoOldFiles {
            get {
                return ResourceManager.GetString("MsgNoOldFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The folder {0} is within HLL&apos;s internal storage area. Please choose another folder that is not a subfolder of {1}..
        /// </summary>
        internal static string OutOfBaseMsg {
            get {
                return ResourceManager.GetString("OutOfBaseMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Choose Another Folder.
        /// </summary>
        internal static string OutOfBaseTitle {
            get {
                return ResourceManager.GetString("OutOfBaseTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Management of Output Files.
        /// </summary>
        internal static string OutputFileManagementDocTitle {
            get {
                return ResourceManager.GetString("OutputFileManagementDocTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Really Delete?.
        /// </summary>
        internal static string ReallyDeleteQuestion {
            get {
                return ResourceManager.GetString("ReallyDeleteQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string SaveBtnCaption {
            get {
                return ResourceManager.GetString("SaveBtnCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Files.
        /// </summary>
        internal static string SaveFilesBtnCaption {
            get {
                return ResourceManager.GetString("SaveFilesBtnCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Files.
        /// </summary>
        internal static string SaveFilesFormTitle {
            get {
                return ResourceManager.GetString("SaveFilesFormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Folder for Document Destination.
        /// </summary>
        internal static string SaveFolderDialogTitle {
            get {
                return ResourceManager.GetString("SaveFolderDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing to Delete.
        /// </summary>
        internal static string TitleNoOldFIles {
            get {
                return ResourceManager.GetString("TitleNoOldFIles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        internal static string YearLabelText {
            get {
                return ResourceManager.GetString("YearLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes, Really Delete Those Files.
        /// </summary>
        internal static string YesReallyDeleteMsg {
            get {
                return ResourceManager.GetString("YesReallyDeleteMsg", resourceCulture);
            }
        }
    }
}
