//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ValleyLabelsAndListsEntities : DbContext
    {
        public ValleyLabelsAndListsEntities()
            : base("name=ValleyLabelsAndListsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<bag_label_info> bag_label_info { get; set; }
        public virtual DbSet<dnr> donors { get; set; }
        public virtual DbSet<gift_label_info> gift_label_info { get; set; }
        public virtual DbSet<services_household_enrollment> services_household_enrollment { get; set; }
    }
}
