//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class services_household_enrollment
    {
        public long id { get; set; }
        public string service_type { get; set; }
        public Nullable<long> year { get; set; }
        public Nullable<long> month { get; set; }
        public Nullable<long> day { get; set; }
        public string head_of_household { get; set; }
        public string phone { get; set; }
        public string address { get; set; }
        public string city { get; set; }
        public string state_or_province { get; set; }
        public string postal_code { get; set; }
    }
}
