//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppWideResources.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AppWideResources.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bag_Labels.
        /// </summary>
        public static string BagLabelBasename {
            get {
                return ResourceManager.GetString("BagLabelBasename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Christmas.
        /// </summary>
        public static string ChristmasFolderName {
            get {
                return ResourceManager.GetString("ChristmasFolderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Writing {0} {1} to file {2}.
        /// </summary>
        public static string CountWritingMsg {
            get {
                return ResourceManager.GetString("CountWritingMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donor_List_{0}_{1}_{2}.xlsx.
        /// </summary>
        public static string DonorListBasefilename {
            get {
                return ResourceManager.GetString("DonorListBasefilename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donor List, {0}, {1}, {2}.
        /// </summary>
        public static string DonorListHeader {
            get {
                return ResourceManager.GetString("DonorListHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} DL {2}.
        /// </summary>
        public static string DonorListWorksheetName {
            get {
                return ResourceManager.GetString("DonorListWorksheetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully created file {0} .
        /// </summary>
        public static string FileCreationSuccessMsg {
            get {
                return ResourceManager.GetString("FileCreationSuccessMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred trying to work with file {0}.
        ///The error message was {1}.
        /// </summary>
        public static string FileExceptionErrorMsg {
            get {
                return ResourceManager.GetString("FileExceptionErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gift_Labels.
        /// </summary>
        public static string GiftLabelBasename {
            get {
                return ResourceManager.GetString("GiftLabelBasename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please include gift receipt..
        /// </summary>
        public static string GiftReceiptRequest {
            get {
                return ResourceManager.GetString("GiftReceiptRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master_List_{0}_{1}_{2}.xlsx.
        /// </summary>
        public static string MasterListBasefilename {
            get {
                return ResourceManager.GetString("MasterListBasefilename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master List, {0}, {1}, {2}.
        /// </summary>
        public static string MasterListHeader {
            get {
                return ResourceManager.GetString("MasterListHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} ML {2}.
        /// </summary>
        public static string MasterListWorksheetName {
            get {
                return ResourceManager.GetString("MasterListWorksheetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --- NO DATA ---.
        /// </summary>
        public static string NoDataMsg {
            get {
                return ResourceManager.GetString("NoDataMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string OtherFolderName {
            get {
                return ResourceManager.GetString("OtherFolderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Bpage &amp;P of &amp;N.
        /// </summary>
        public static string PageNumbers {
            get {
                return ResourceManager.GetString("PageNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Participant_List_{0}_{1}.xlsx.
        /// </summary>
        public static string ParticipantListBasefilename {
            get {
                return ResourceManager.GetString("ParticipantListBasefilename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Participant List, {0}, {1}.
        /// </summary>
        public static string ParticipantListHeader {
            get {
                return ResourceManager.GetString("ParticipantListHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postcard_Labels.
        /// </summary>
        public static string PostcardLabelBasename {
            get {
                return ResourceManager.GetString("PostcardLabelBasename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanksgiving.
        /// </summary>
        public static string ThanksgivingFolderName {
            get {
                return ResourceManager.GetString("ThanksgivingFolderName", resourceCulture);
            }
        }
    }
}
