//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppWideResources.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AppWideResources.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All sections processed OK.
        /// </summary>
        public static string AllSectionsProcessedOKMsg {
            get {
                return ResourceManager.GetString("AllSectionsProcessedOKMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bag_Labels_{0}_{1}_{2}.xlsx.
        /// </summary>
        public static string BagLabelBaseFilename {
            get {
                return ResourceManager.GetString("BagLabelBaseFilename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Christmas.
        /// </summary>
        public static string ChristmasFolderName {
            get {
                return ResourceManager.GetString("ChristmasFolderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found {0} data sections..
        /// </summary>
        public static string CountOfDataSectionsMsg {
            get {
                return ResourceManager.GetString("CountOfDataSectionsMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Writing {0} {1} to file {2}.
        /// </summary>
        public static string CountWritingMsg {
            get {
                return ResourceManager.GetString("CountWritingMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found {0} data sections..
        /// </summary>
        public static string DataSectionsFoundMsg {
            get {
                return ResourceManager.GetString("DataSectionsFoundMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click &quot;Yes&quot; to confirm deletion of backup files..
        /// </summary>
        public static string DelBackupConfirmPrompt {
            get {
                return ResourceManager.GetString("DelBackupConfirmPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm File Deletion.
        /// </summary>
        public static string DelBackupConfirmTitle {
            get {
                return ResourceManager.GetString("DelBackupConfirmTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while trying to delete backup files. The error text is: {0}.
        /// </summary>
        public static string DelBackupErrorMsg {
            get {
                return ResourceManager.GetString("DelBackupErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Files From Previous Years.
        /// </summary>
        public static string DeleteOldFilesTitle {
            get {
                return ResourceManager.GetString("DeleteOldFilesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HLLDocumentation - General.
        /// </summary>
        public static string DocGeneralTitle {
            get {
                return ResourceManager.GetString("DocGeneralTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donor_List_{0}_{1}_{2}.xlsx.
        /// </summary>
        public static string DonorListBasefilename {
            get {
                return ResourceManager.GetString("DonorListBasefilename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donor List, {0}, {1}, {2}.
        /// </summary>
        public static string DonorListHeader {
            get {
                return ResourceManager.GetString("DonorListHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} DL {2}.
        /// </summary>
        public static string DonorListWorksheetName {
            get {
                return ResourceManager.GetString("DonorListWorksheetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully added {0} label and/or list files.
        /// </summary>
        public static string FileAddingSuccessMsg {
            get {
                return ResourceManager.GetString("FileAddingSuccessMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully created file {0} .
        /// </summary>
        public static string FileCreationSuccessMsg {
            get {
                return ResourceManager.GetString("FileCreationSuccessMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred trying to work with file {0}.
        ///The error message was {1}.
        /// </summary>
        public static string FileExceptionErrorMsg {
            get {
                return ResourceManager.GetString("FileExceptionErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File {0} does not exist..
        /// </summary>
        public static string FileNotFoundMsg {
            get {
                return ResourceManager.GetString("FileNotFoundMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Not Found.
        /// </summary>
        public static string FileNotFoundTitle {
            get {
                return ResourceManager.GetString("FileNotFoundTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel Files (*.XLS;*XLS?)|*.XLS;*.XLS?.
        /// </summary>
        public static string FileSpecFilterExcel {
            get {
                return ResourceManager.GetString("FileSpecFilterExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generating output files....
        /// </summary>
        public static string GeneratingOutputFilesMsg {
            get {
                return ResourceManager.GetString("GeneratingOutputFilesMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gift_Labels_{0}_{1}_{2}.xlsx.
        /// </summary>
        public static string GiftLabelBaseFilename {
            get {
                return ResourceManager.GetString("GiftLabelBaseFilename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please include gift receipt..
        /// </summary>
        public static string GiftReceiptRequest {
            get {
                return ResourceManager.GetString("GiftReceiptRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} does not appear to b e a valid Excel worksheet..
        /// </summary>
        public static string InvalidWorksheetMsg {
            get {
                return ResourceManager.GetString("InvalidWorksheetMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master_List_{0}_{1}_{2}.xlsx.
        /// </summary>
        public static string MasterListBasefilename {
            get {
                return ResourceManager.GetString("MasterListBasefilename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master List, {0}, {1}, {2}.
        /// </summary>
        public static string MasterListHeader {
            get {
                return ResourceManager.GetString("MasterListHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} ML {2}.
        /// </summary>
        public static string MasterListWorksheetName {
            get {
                return ResourceManager.GetString("MasterListWorksheetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --- NO DATA ---.
        /// </summary>
        public static string NoDataMsg {
            get {
                return ResourceManager.GetString("NoDataMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No files match the selected criteria..
        /// </summary>
        public static string NoMatchingFilesMsg {
            get {
                return ResourceManager.GetString("NoMatchingFilesMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select different criteria for Document Type to View, Year, and/or Donor.
        /// </summary>
        public static string NoMatchingFilesTooltip {
            get {
                return ResourceManager.GetString("NoMatchingFilesTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no label or list files available for viewing.\nPlease click &quot;Process VESTAReports&quot;\nand select one or more reports..
        /// </summary>
        public static string NoOutputFilesMsg {
            get {
                return ResourceManager.GetString("NoOutputFilesMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Add VESTA Reports.
        /// </summary>
        public static string NoOutputFilesTitle {
            get {
                return ResourceManager.GetString("NoOutputFilesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You may now close this window..
        /// </summary>
        public static string OKToCloseMsg {
            get {
                return ResourceManager.GetString("OKToCloseMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing report {0}.
        /// </summary>
        public static string OpeningReportMsg {
            get {
                return ResourceManager.GetString("OpeningReportMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string OtherFolderName {
            get {
                return ResourceManager.GetString("OtherFolderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Bpage &amp;P of &amp;N.
        /// </summary>
        public static string PageNumbers {
            get {
                return ResourceManager.GetString("PageNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Participant_List_{0}_{1}.xlsx.
        /// </summary>
        public static string ParticipantListBasefilename {
            get {
                return ResourceManager.GetString("ParticipantListBasefilename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Participant List, {0}, {1}.
        /// </summary>
        public static string ParticipantListHeader {
            get {
                return ResourceManager.GetString("ParticipantListHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postcard_Labels_{0}_{1}.xlsx.
        /// </summary>
        public static string PostcardLabelBaseFilename {
            get {
                return ResourceManager.GetString("PostcardLabelBaseFilename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing cancelled..
        /// </summary>
        public static string ProcessingCancelledMsg {
            get {
                return ResourceManager.GetString("ProcessingCancelledMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing data section {0} of {1}.
        /// </summary>
        public static string ProcessingDataSectionsMsg {
            get {
                return ResourceManager.GetString("ProcessingDataSectionsMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report results.
        /// </summary>
        public static string ResultsSheetDefaultName {
            get {
                return ResourceManager.GetString("ResultsSheetDefaultName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching for data sections in this VESTA report....
        /// </summary>
        public static string SearchingForDataSectionsMsg {
            get {
                return ResourceManager.GetString("SearchingForDataSectionsMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All sections processed OK.
        /// </summary>
        public static string SectionsProcessedSuccessMsg {
            get {
                return ResourceManager.GetString("SectionsProcessedSuccessMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing data section {0} of {1}....
        /// </summary>
        public static string SectionXOfYMsg {
            get {
                return ResourceManager.GetString("SectionXOfYMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Years.
        /// </summary>
        public static string SelectYears {
            get {
                return ResourceManager.GetString("SelectYears", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} not found in {1}.
        /// </summary>
        public static string SheetNotFoundInFileMsg {
            get {
                return ResourceManager.GetString("SheetNotFoundInFileMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only {0} sections processed OK (out of {1}).
        /// </summary>
        public static string SomeSectionsNotProcessedMsg {
            get {
                return ResourceManager.GetString("SomeSectionsNotProcessedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing report {0}.
        /// </summary>
        public static string StartingEachReportMsg {
            get {
                return ResourceManager.GetString("StartingEachReportMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanksgiving.
        /// </summary>
        public static string ThanksgivingFolderName {
            get {
                return ResourceManager.GetString("ThanksgivingFolderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} report type is unknown..
        /// </summary>
        public static string UnknownReportTypeMsg {
            get {
                return ResourceManager.GetString("UnknownReportTypeMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing {0} VESTAReports.
        /// </summary>
        public static string VestaReportCountMsg {
            get {
                return ResourceManager.GetString("VestaReportCountMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error during processing of the VESTA reports. The error text is:  {0}.
        /// </summary>
        public static string VestaReportExceptionMsg {
            get {
                return ResourceManager.GetString("VestaReportExceptionMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting processing of VESTA reports....
        /// </summary>
        public static string VestaReportProcessingStartMsg {
            get {
                return ResourceManager.GetString("VestaReportProcessingStartMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select one or more VESTA Reports.
        /// </summary>
        public static string VestaReportSelectTitle {
            get {
                return ResourceManager.GetString("VestaReportSelectTitle", resourceCulture);
            }
        }
    }
}
